# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
    build:
        working_directory: ~/tmp
        docker:
            - image: "circleci/node:10"
        steps:
            - checkout
            - run: npm start
            - run: cd client
            - run: npm install
            - run: npm test
